"""Compile CadIrV2 to generated parts/*.py with embedded numbers."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from cad_runtime.ir.params import ParamError, resolve_params, resolve_scalar
from cad_runtime.ir.schema import IrError, validate_document


def _n(value: Any, env: dict[str, float], label: str) -> float:
    number = resolve_scalar(value, env, label)
    if number != number or abs(number) == float("inf"):
        raise IrError(f"{label} resolved to a non-finite number")
    return number


def _vec(value: Any, env: dict[str, float], label: str) -> tuple[float, ...]:
    return tuple(_n(item, env, f"{label}[{i}]") for i, item in enumerate(value))


def _fmt(value: float) -> str:
    text = f"{value:.10g}"
    return text if "." in text or "e" in text.lower() else f"{text}.0"


def _tuple(values: tuple[float, ...]) -> str:
    return "(" + ", ".join(_fmt(item) for item in values) + ("," if len(values) == 1 else "") + ")"


def _axis_dir(value: Any, env: dict[str, float], label: str) -> tuple[float, float, float]:
    if value == "X":
        return (1.0, 0.0, 0.0)
    if value == "Y":
        return (0.0, 1.0, 0.0)
    if value == "Z":
        return (0.0, 0.0, 1.0)
    vec = _vec(value, env, label)
    return (vec[0], vec[1], vec[2])


def _plane_expr(plane: dict[str, Any], env: dict[str, float]) -> str:
    name = {"XY": "Plane.XY", "XZ": "Plane.XZ", "YZ": "Plane.YZ"}[plane["plane"]]
    if "offset" in plane:
        return f"{name}.offset({_fmt(_n(plane['offset'], env, 'plane.offset'))})"
    return name


def _profile_expr(profile: dict[str, Any], env: dict[str, float], label: str) -> str:
    center = profile.get("center")
    shift = ""
    if center is not None:
        cu, cv = _vec(center, env, f"{label}.center")
        if cu or cv:
            shift = f".moved(Location(({_fmt(cu)}, {_fmt(cv)}, 0.0)))"
    if profile["kind"] == "rect":
        width = _n(profile["width"], env, f"{label}.width")
        height = _n(profile["height"], env, f"{label}.height")
        if width <= 0 or height <= 0:
            raise IrError(f"{label} width/height must be positive")
        radius = _n(profile["corner_radius"], env, f"{label}.corner_radius") if "corner_radius" in profile else 0.0
        if radius > 0:
            return f"Rectangle({_fmt(width)}, {_fmt(height)}, rotation=0.0, align=(Align.CENTER, Align.CENTER)).fillet({_fmt(radius)}){shift}"
        return f"Rectangle({_fmt(width)}, {_fmt(height)}){shift}"
    diameter = _n(profile["diameter"], env, f"{label}.diameter")
    if diameter <= 0:
        raise IrError(f"{label} diameter must be positive")
    return f"Circle({_fmt(diameter / 2.0)}){shift}"


def _positive(value: float, label: str) -> float:
    if value <= 0:
        raise IrError(f"{label} must be positive")
    return value


def compile_document(document: Any, params_source: str) -> str:
    doc = validate_document(document)
    env = resolve_params(params_source)
    for name in doc["params"]:
        if name not in env:
            raise ParamError(f"IR declares unknown parameter {name}")
    lines = [
        '"""Generated by CAD IR compiler. Do not edit; change ir/<part>.json."""',
        "from build123d import *",
        "",
        "",
        "def build():",
    ]
    solids: set[str] = set()
    sketches: set[str] = set()
    paths: set[str] = set()
    for op in doc["ops"]:
        oid = op["id"]
        kind = op["op"]
        if kind == "sketch":
            expr = _profile_expr(op["profile"], env, f"{oid}.profile")
            lines.append(f"    {oid} = {_plane_expr(op['plane'], env)} * {expr}")
            sketches.add(oid)
        elif kind == "path":
            points = [_vec(point, env, f"{oid}.points") for point in op["points"]]
            if op["kind"] == "line":
                if points[0] == points[1]:
                    raise IrError(f"{oid} line points must be distinct")
                lines.append(f"    {oid} = Line({_tuple(points[0])}, {_tuple(points[1])})")
            else:
                pts = ", ".join(_tuple(point) for point in points)
                lines.append(f"    {oid} = Spline({pts})")
            paths.add(oid)
        elif kind == "primitive":
            pkind = op["kind"]
            if pkind == "box":
                size = _vec(op["size"], env, f"{oid}.size")
                origin = _vec(op["origin"], env, f"{oid}.origin") if "origin" in op else (0.0, 0.0, 0.0)
                _positive(size[0], f"{oid}.size[0]")
                _positive(size[1], f"{oid}.size[1]")
                _positive(size[2], f"{oid}.size[2]")
                cx, cy, cz = origin[0] + size[0] / 2.0, origin[1] + size[1] / 2.0, origin[2] + size[2] / 2.0
                lines.append(f"    {oid} = Location(({_fmt(cx)}, {_fmt(cy)}, {_fmt(cz)})) * Box({_fmt(size[0])}, {_fmt(size[1])}, {_fmt(size[2])})")
            elif pkind in ("cylinder", "cone"):
                radius = _positive(_n(op["radius"], env, f"{oid}.radius"), f"{oid}.radius")
                height = _positive(_n(op["height"], env, f"{oid}.height"), f"{oid}.height")
                origin = _vec(op["axis"]["origin"], env, f"{oid}.axis.origin")
                direction = _axis_dir(op["axis"]["direction"], env, f"{oid}.axis.direction")
                if pkind == "cone":
                    radius2 = _n(op["radius2"], env, f"{oid}.radius2")
                    if radius2 < 0:
                        raise IrError(f"{oid}.radius2 must be >= 0")
                    prim = f"Cone({_fmt(radius)}, {_fmt(radius2)}, {_fmt(height)})"
                else:
                    prim = f"Cylinder({_fmt(radius)}, {_fmt(height)})"
                lines.append(
                    f"    {oid} = Plane({_tuple(origin)}, z_dir={_tuple(direction)}) * "
                    f"{prim.replace(')', ', align=(Align.CENTER, Align.CENTER, Align.MIN))')}"
                )
            else:
                radius = _positive(_n(op["radius"], env, f"{oid}.radius"), f"{oid}.radius")
                center = _vec(op["center"], env, f"{oid}.center") if "center" in op else (0.0, 0.0, 0.0)
                lines.append(f"    {oid} = Location({_tuple(center)}) * Sphere({_fmt(radius)})")
            solids.add(oid)
        elif kind == "extrude":
            if op["sketch"] not in sketches:
                raise IrError(f"{oid}.sketch must reference a sketch op")
            amount = _n(op["amount"], env, f"{oid}.amount")
            if amount == 0:
                raise IrError(f"{oid}.amount must be non-zero")
            both = bool(op.get("both"))
            lines.append(f"    {oid} = extrude({op['sketch']}, amount={_fmt(amount)}, both={both})")
            solids.add(oid)
        elif kind == "loft":
            stations = op["stations"]
            ts = [_n(row["t"], env, f"{oid}.stations.t") for row in stations]
            if any(ts[i] >= ts[i + 1] for i in range(len(ts) - 1)):
                raise IrError(f"{oid} station t values must strictly increase")
            axis = op["axis"]
            plane = {"X": "Plane.YZ", "Y": "Plane.XZ", "Z": "Plane.XY"}[axis]
            names: list[str] = []
            for i, row in enumerate(stations):
                sec = f"{oid}_s{i}"
                names.append(sec)
                expr = _profile_expr(row["profile"], env, f"{oid}.stations[{i}]")
                offset = _fmt(ts[i])
                move = ""
                if "center" in row:
                    cu, cv = _vec(row["center"], env, f"{oid}.stations[{i}].center")
                    if axis == "X":
                        move = f".moved(Location((0.0, {_fmt(cu)}, {_fmt(cv)})))"
                    elif axis == "Y":
                        move = f".moved(Location(({_fmt(cu)}, 0.0, {_fmt(cv)})))"
                    else:
                        move = f".moved(Location(({_fmt(cu)}, {_fmt(cv)}, 0.0)))"
                rot = ""
                if "rotation" in row:
                    angle = _n(row["rotation"], env, f"{oid}.stations[{i}].rotation")
                    rot_axis = {"X": "(1, 0, 0)", "Y": "(0, 1, 0)", "Z": "(0, 0, 1)"}[axis]
                    rot = f".rotate(Axis((0, 0, 0), {rot_axis}), {_fmt(angle)})"
                lines.append(f"    {sec} = {plane}.offset({offset}) * {expr}{move}{rot}")
            lines.append(f"    {oid} = loft([{', '.join(names)}])")
            solids.add(oid)
        elif kind == "sweep":
            if op["path"] not in paths:
                raise IrError(f"{oid}.path must reference a path op")
            expr = _profile_expr(op["section"], env, f"{oid}.section")
            lines.append(f"    {oid}_sec = Plane({op['path']} @ 0, z_dir={op['path']} % 0) * {expr}")
            lines.append(f"    {oid} = sweep({oid}_sec, path={op['path']})")
            solids.add(oid)
        elif kind == "hole":
            if op["on"] not in solids:
                raise IrError(f"{oid}.on must reference a solid")
            origin = _vec(op["origin"], env, f"{oid}.origin")
            direction = _axis_dir(op["direction"], env, f"{oid}.direction")
            diameter = _positive(_n(op["diameter"], env, f"{oid}.diameter"), f"{oid}.diameter")
            if op["depth"] == "through":
                depth = 10000.0
                start = (origin[0] - direction[0] * 5000.0, origin[1] - direction[1] * 5000.0, origin[2] - direction[2] * 5000.0)
            else:
                depth = _positive(_n(op["depth"], env, f"{oid}.depth"), f"{oid}.depth")
                start = origin
            lines.append(
                f"    {oid}_cut = Plane(({_fmt(start[0])}, {_fmt(start[1])}, {_fmt(start[2])}), z_dir={_tuple(direction)}) * "
                f"Cylinder({_fmt(diameter / 2.0)}, {_fmt(depth)}, align=(Align.CENTER, Align.CENTER, Align.MIN))"
            )
            lines.append(f"    {oid} = {op['on']} - {oid}_cut")
            solids.add(oid)
        elif kind == "boolean":
            if op["a"] not in solids or op["b"] not in solids:
                raise IrError(f"{oid} boolean operands must be solids")
            op_map = {"fuse": "+", "cut": "-", "intersect": "&"}
            lines.append(f"    {oid} = {op['a']} {op_map[op['kind']]} {op['b']}")
            solids.add(oid)
        elif kind == "pattern":
            if op["on"] not in solids:
                raise IrError(f"{oid}.on must reference a solid")
            count = int(op["pattern"]["count"])
            if op["pattern"]["kind"] == "linear":
                spacing = _positive(_n(op["pattern"]["spacing"], env, f"{oid}.spacing"), f"{oid}.spacing")
                direction = _axis_dir(op["pattern"]["direction"], env, f"{oid}.direction")
                lines.append(f"    {oid}_parts = [{op['on']}]")
                lines.append(f"    for _i in range(1, {count}):")
                lines.append(
                    f"        {oid}_parts.append(Location(({_fmt(direction[0] * spacing)} * _i, {_fmt(direction[1] * spacing)} * _i, {_fmt(direction[2] * spacing)} * _i)) * {op['on']})"
                )
            else:
                angle = _n(op["pattern"]["angle"], env, f"{oid}.angle")
                if angle <= 0 or angle > 360:
                    raise IrError(f"{oid}.angle must be in (0, 360]")
                origin = _vec(op["pattern"]["axis"]["origin"], env, f"{oid}.axis.origin")
                direction = _axis_dir(op["pattern"]["axis"]["direction"], env, f"{oid}.axis.direction")
                step = angle / count
                lines.append(f"    {oid}_parts = [{op['on']}]")
                lines.append(f"    for _i in range(1, {count}):")
                lines.append(
                    f"        {oid}_parts.append({op['on']}.rotate(Axis({_tuple(origin)}, {_tuple(direction)}), {_fmt(step)} * _i))"
                )
            if op["combine"] == "fuse":
                lines.append(f"    {oid} = {oid}_parts[0]")
                lines.append(f"    for _p in {oid}_parts[1:]:")
                lines.append(f"        {oid} = {oid} + _p")
            else:
                lines.append(f"    {oid} = Compound({oid}_parts)")
            solids.add(oid)
        elif kind == "transform":
            if op["on"] not in solids:
                raise IrError(f"{oid}.on must reference a solid")
            expr = op["on"]
            if "rotate" in op:
                origin = _vec(op["rotate"]["axis"]["origin"], env, f"{oid}.rotate.origin")
                direction = _axis_dir(op["rotate"]["axis"]["direction"], env, f"{oid}.rotate.direction")
                angle = _n(op["rotate"]["angle"], env, f"{oid}.rotate.angle")
                expr = f"{expr}.rotate(Axis({_tuple(origin)}, {_tuple(direction)}), {_fmt(angle)})"
            if "move" in op:
                move = _vec(op["move"], env, f"{oid}.move")
                expr = f"Location({_tuple(move)}) * {expr}"
            lines.append(f"    {oid} = {expr}")
            solids.add(oid)
    if doc["show"] not in solids:
        raise IrError(f"ir.show {doc['show']} is not a solid")
    lines.append(f"    return {doc['show']}")
    lines.append("")
    return "\n".join(lines)


def compile_part(ir_path: Path, params_path: Path) -> str:
    try:
        document = json.loads(ir_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise IrError(f"invalid IR JSON: {exc}") from exc
    params_source = params_path.read_text(encoding="utf-8") if params_path.is_file() else ""
    return compile_document(document, params_source)
