const COMMANDS = ["serve", "status", "repair", "remove", "upgrade", "service"] as const
const SERVICE_ACTIONS = ["install", "uninstall", "start", "stop", "restart", "status"] as const
const SHELLS = ["bash", "zsh"] as const

export type CompletionShell = (typeof SHELLS)[number]

export function isCompletionShell(value: string): value is CompletionShell {
  return (SHELLS as readonly string[]).includes(value)
}

export function bashCompletionScript(): string {
  const commands = COMMANDS.join(" ")
  const serviceActions = SERVICE_ACTIONS.join(" ")
  return [
    `# opencode-studio bash completion (installed by package postinstall)`,
    `_opencode_studio() {`,
    `  local cur prev words cword`,
    `  if declare -F _init_completion >/dev/null 2>&1; then`,
    `    _init_completion || return`,
    `  else`,
    `    COMPREPLY=()`,
    `    cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `    prev="\${COMP_WORDS[COMP_CWORD-1]}"`,
    `    words=("\${COMP_WORDS[@]}")`,
    `    cword=$COMP_CWORD`,
    `  fi`,
    ``,
    `  local commands="${commands}"`,
    `  local service_actions="${serviceActions}"`,
    `  local global_opts="--workspace --help -h -v --version"`,
    `  local serve_opts="--workspace --local --web --port --ui-directory --help -h"`,
    `  local service_opts="--workspace --local --web --port --name --json --help -h"`,
    `  local upgrade_opts="--check --workspace --local --web --port --name --json --help -h"`,
    `  local repair_opts="--workspace --dry-run --json --help -h"`,
    `  local status_opts="--workspace --json --help -h"`,
    ``,
    `  case "$prev" in`,
    `    --workspace|--ui-directory)`,
    `      if declare -F _filedir >/dev/null 2>&1; then _filedir -d; else COMPREPLY=($(compgen -d -- "$cur")); fi`,
    `      return`,
    `      ;;`,
    `    --port)`,
    `      COMPREPLY=($(compgen -W "4173 4174 8080" -- "$cur"))`,
    `      return`,
    `      ;;`,
    `    --name)`,
    `      COMPREPLY=($(compgen -W "opencode-studio" -- "$cur"))`,
    `      return`,
    `      ;;`,
    `  esac`,
    ``,
    `  local cmd="" action=""`,
    `  local i`,
    `  for ((i = 1; i < cword; i++)); do`,
    `    case "\${words[i]}" in`,
    `      -*|--) ;;`,
    `      *)`,
    `        if [[ -z "$cmd" ]]; then cmd="\${words[i]}"`,
    `        elif [[ "$cmd" == service && -z "$action" ]]; then action="\${words[i]}"`,
    `        fi`,
    `        ;;`,
    `    esac`,
    `  done`,
    ``,
    `  if [[ -z "$cmd" ]]; then`,
    `    COMPREPLY=($(compgen -W "$commands $global_opts" -- "$cur"))`,
    `    return`,
    `  fi`,
    ``,
    `  if [[ "$cur" == -* ]]; then`,
    `    case "$cmd" in`,
    `      repair) COMPREPLY=($(compgen -W "$repair_opts" -- "$cur")) ;;`,
    `      status|remove) COMPREPLY=($(compgen -W "$status_opts" -- "$cur")) ;;`,
    `      serve) COMPREPLY=($(compgen -W "$serve_opts" -- "$cur")) ;;`,
    `      service) COMPREPLY=($(compgen -W "$service_opts" -- "$cur")) ;;`,
    `      upgrade) COMPREPLY=($(compgen -W "$upgrade_opts" -- "$cur")) ;;`,
    `      *) COMPREPLY=($(compgen -W "$global_opts" -- "$cur")) ;;`,
    `    esac`,
    `    return`,
    `  fi`,
    ``,
    `  case "$cmd" in`,
    `    service)`,
    `      if [[ -z "$action" ]]; then`,
    `        COMPREPLY=($(compgen -W "$service_actions" -- "$cur"))`,
    `      else`,
    `        COMPREPLY=($(compgen -W "$service_opts" -- "$cur"))`,
    `      fi`,
    `      ;;`,
    `    *)`,
    `      COMPREPLY=()`,
    `      ;;`,
    `  esac`,
    `}`,
    ``,
    `complete -F _opencode_studio opencode-studio`,
    ``,
  ].join("\n")
}

export function zshCompletionScript(): string {
  const serviceWords = SERVICE_ACTIONS.map((c) => `'${c}'`).join(" ")
  return [
    `# opencode-studio zsh completion (installed by package postinstall)`,
    `_opencode_studio() {`,
    `  local -a commands service_actions`,
    `  commands=(${COMMANDS.map((c) => `'${c}'`).join(" ")})`,
    `  service_actions=(${serviceWords})`,
    ``,
    `  local context state line`,
    `  typeset -A opt_args`,
    ``,
    `  _arguments -C `,
    `    '(-h --help)'{-h,--help}'[Show help]' `,
    `    '(-v --version)'{-v,--version}'[Show version]' `,
    `    '1: :->command' `,
    `    '*:: :->args' && return`,
    ``,
    `  case $state in`,
    `    command)`,
    `      _describe -t commands 'command' commands`,
    `      ;;`,
    `    args)`,
    `      case $words[1] in`,
    `        repair)`,
    `          _arguments `,
    `            '--workspace[Domain data root]:dir:_files -/' `,
    `            '--dry-run[Print actions without writing]' `,
    `            '--json[JSON output]'`,
    `          ;;`,
    `        status|remove)`,
    `          _arguments `,
    `            '--workspace[Domain data root]:dir:_files -/' `,
    `            '--json[JSON output]'`,
    `          ;;`,
    `        serve)`,
    `          _arguments \\`,
    `            '--workspace[Domain data root]:dir:_files -/' \\`,
    `            '--local[Bind 127.0.0.1 (default)]' \\`,
    `            '--web[Bind 0.0.0.0; requires OPENCODE_STUDIO_PASSWORD]' \\`,
    `            '--port[Bind port]:port:(4173 4174 8080)' \\`,
    `            '--ui-directory[UI dist path]:dir:_files -/'`,
    `          ;;`,
    `        upgrade)`,
    `          _arguments \\`,
    `            '--check[Only check whether an update is available]' \\`,
    `            '--workspace[Domain data root]:dir:_files -/' \\`,
    `            '--local[Bind 127.0.0.1 when refreshing unit]' \\`,
    `            '--web[Bind 0.0.0.0 when refreshing unit]' \\`,
    `            '--port[Bind port]:port:(4173 4174 8080)' \\`,
    `            '--name[systemd unit name]:name:(opencode-studio)' \\`,
    `            '--json[JSON output]'`,
    `          ;;`,
    `        service)`,
    `          _arguments \\`,
    `            '1:action:($service_actions)' \\`,
    `            '--workspace[Domain data root]:dir:_files -/' \\`,
    `            '--local[Bind 127.0.0.1 (default on install)]' \\`,
    `            '--web[Bind 0.0.0.0; requires OPENCODE_STUDIO_PASSWORD]' \\`,
    `            '--port[Bind port]:port:(4173 4174 8080)' \\`,
    `            '--name[systemd unit name]:name:(opencode-studio)' \\`,
    `            '--json[JSON output]'`,
    `          ;;`,
    `      esac`,
    `      ;;`,
    `  esac`,
    `}`,
    ``,
    `compdef _opencode_studio opencode-studio`,
    ``,
  ].join("\n")
}

export function completionScript(shell: CompletionShell): string {
  return shell === "zsh" ? zshCompletionScript() : bashCompletionScript()
}
